<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRBTCU2u\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRBTCU2u/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRBTCU2u.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRBTCU2u\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRBTCU2u\App_KernelDevDebugContainer([
    'container.build_hash' => 'RBTCU2u',
    'container.build_id' => 'f3c757d6',
    'container.build_time' => 1740063107,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRBTCU2u');
